name: dist-build-flow

on:
  push:
    branches: [master]
    paths-ignore: [.github/workflows/**, ./LICENSE, ./README.md ./gitignore]

env:
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ACTION_BOT_NAME: github-actions[bot]
  ACTION_BOT_EMAIL: github-actions[bot]@users.noreply.github.com
  BRANCH_SOURCE: master
  BRANCH_GITHUB_PAGES: github-pages
  DINGTALK_ROBOT_ACCESS_TOKEN: ${{ secrets.DINGTALK_ROBOT_ACCESS_TOKEN }}
  RENDER_BARK_SERVER: ${{ secrets.RENDER_BARK_SERVER }}
  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  CLOUDFLARE_USER_EMAIL: ${{ secrets.CLOUDFLARE_USER_EMAIL }}
  CLOUDFLARE_PURGE_CACHE_API_TOKEN: ${{ secrets.CLOUDFLARE_PURGE_CACHE_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout ${{ env.BRANCH_SOURCE }}
        uses: actions/checkout@v3
        with:
          path: ${{ env.BRANCH_SOURCE }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          cd ${{ env.BRANCH_SOURCE }}
          npm install
          npm run build ngx-uvcanvas
          npm run build site

      - name: Checkout ${{ env.BRANCH_GITHUB_PAGES }}
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_GITHUB_PAGES }}
          path: ${{ env.BRANCH_GITHUB_PAGES }}

      - name: Copy Files
        run: |
          generatedDateStr="$(date +%Y-%m-%d\ %H:%M:%S\ %z)"
          echo $generatedDateStr > ./${{ env.BRANCH_GITHUB_PAGES }}/generated.txt
          sed "s/{{\$date}}/$generatedDateStr/" ./${{ env.BRANCH_SOURCE }}/generated.template.svg > ./${{ env.BRANCH_GITHUB_PAGES }}/generated.svg
          cp -r ./${{ env.BRANCH_SOURCE }}/dist/site/browser/* ./${{ env.BRANCH_GITHUB_PAGES }}
          cp -r ./${{ env.BRANCH_SOURCE }}/dist/site/* ./${{ env.BRANCH_GITHUB_PAGES }}
          cp ./${{ env.BRANCH_SOURCE }}/.gitignore ./${{ env.BRANCH_GITHUB_PAGES }}
          ls -al ./${{ env.BRANCH_SOURCE }}
          ls -al ./${{ env.BRANCH_GITHUB_PAGES }}

      - name: Deploy
        run: |
          cd ${{ env.BRANCH_GITHUB_PAGES }}
          git add .
          git config user.name $ACTION_BOT_NAME
          git config user.email $ACTION_BOT_EMAIL
          git commit -m "Site updated: $(date +%Y-%m-%d\ %H:%M:%S\ %z)"
          git push

      - name: Cloudflare Purge Cache
        continue-on-error: true
        run: |
          curl --write-out %{http_code} \
          --silent \
          --output /dev/null \
          --request POST \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer '$CLOUDFLARE_PURGE_CACHE_API_TOKEN \
          --url 'https://api.cloudflare.com/client/v4/zones/'$CLOUDFLARE_ZONE_ID'/purge_cache' \
          --data '{
              "purge_everything": true
          }'

      - name: DingTalk
        continue-on-error: true
        run: |
          cd ${{ env.BRANCH_SOURCE }}
          curl --request POST \
          --url 'https://oapi.dingtalk.com/robot/send?access_token='$DINGTALK_ROBOT_ACCESS_TOKEN \
          --header 'Content-Type: application/json' \
          --data '{
            "msgtype": "text",
            "at": {
              isAtAll: true
              },
            "text": {
              "content": "#### Github-actions[bot] Notification #### \n*项目名称： ngx-uvcanvas.ife.app \n*日期： '"$(date +%Y-%m-%d\ %H:%M:%S\ %z)"' \n*路径： '"$(pwd)"' \n*Git地址： \n'"$(git remote -v)"' \n*分支： '"$(git name-rev --name-only HEAD)"' \n*最后提交： \n'"$(git show -s)"' \n*Build机器信息： \n'"$(uname -a)"' \n*Build机器IP： \n'"$(ip address | grep 'inet' | awk '{print $2}')"' \n\n我就是我, 是颜色不一样的烟火"
              }
            }'

      - name: Bark
        continue-on-error: true
        run: |
          curl --location $RENDER_BARK_SERVER'/push' \
          --header 'Content-Type: application/json; charset=utf-8' \
          --data '{
          "body": "tedding.dev build completed ",
          "title": "Github-actions[bot]",
          "device_key": "bark",
          "icon": "https://github.com/fluidicon.png",
          "group": "Github-actions[bot]",
          "url": "https://github.com/teddingdev/teddingdev.github.io/actions"
          }'
